import { useState, useEffect } from 'react';

let currentLanguage = localStorage.getItem('appLanguage') || 'si';
const listeners = new Set();

export const getLanguage = () => currentLanguage;

export const setLanguage = (lang) => {
  if (lang !== currentLanguage) {
    currentLanguage = lang;
    localStorage.setItem('appLanguage', lang);
    listeners.forEach((listener) => listener(lang));
    window.dispatchEvent(new CustomEvent('languageChange', { detail: lang }));
  }
};

export const useLanguage = () => {
  const [lang, setLangState] = useState(currentLanguage);

  useEffect(() => {
    const handleUpdate = (newLang) => setLangState(newLang);
    listeners.add(handleUpdate);
    return () => {
      listeners.delete(handleUpdate);
    };
  }, []);

  return [lang, setLanguage];
};

export const translations = {
  en: {
    nav: {
      noticeboard: "Noticeboard",
      appointments: "Appointments",
      profile: "Profile",
      certificates: "Certificates",
      welfareApply: "Welfare Apply",
      disaster: "🌊 Disaster",
      complaints: "🏗️ Complaints",
      election: "🗳️ Election",
      gnDashboard: "GN Dashboard",
      welfareManage: "Welfare Manage",
      systemSettings: "System Settings",
      disasterManage: "Disaster",
      infraManage: "Infra",
      electionManage: "Election",
      logout: "Logout",
      login: "Login",
      register: "Register"
    },
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      submit: "Submit",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      update: "Update",
      status: "Status",
      action: "Action",
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      active: "Active",
      suspended: "Suspended",
      resolved: "Resolved"
    },
    disaster: {
      title: "Disaster & Emergency Portal",
      sos: "SOS",
      sendSos: "Send Emergency SOS",
      alerts: "Emergency Alerts",
      shelters: "Safe Shelters",
      mySos: "My SOS History",
      contacts: "Emergency Contacts",
      noAlerts: "No active emergency alerts at this time.",
      noShelters: "No safe shelters registered.",
      noSos: "You have not submitted any SOS requests.",
      sosFormTitle: "Emergency SOS Request",
      sosFormHelp: "What help do you need?",
      sosFormLoc: "Current Location / Address",
      sosFormDesc: "Additional details (injuries, hazards, etc.)",
      sosFormPersons: "Number of persons affected",
      submitting: "Submitting...",
      sosSubmitted: "Emergency SOS Request submitted successfully! Authorities have been notified.",
      capacity: "Capacity",
      facilities: "Facilities",
      callNow: "Call Now",
      officerTitle: "Disaster Management Officer",
      overview: "Overview",
      totalAlerts: "Total Alerts",
      activeAlerts: "Active Alerts",
      totalSos: "Total SOS Requests",
      pendingSos: "Pending SOS Requests",
      postAlert: "Post New Alert",
      editAlert: "Edit Alert",
      alertTitle: "Alert Title",
      severity: "Severity",
      affectedArea: "Affected Area",
      instructions: "Instructions",
      low: "Low",
      medium: "Medium",
      high: "High",
      critical: "Critical",
      sosRequests: "SOS Requests",
      markProgress: "Mark In Progress",
      resolve: "Resolve",
      addNote: "Add resolution note"
    },
    infra: {
      title: "Infrastructure Issues Portal",
      submitTitle: "Submit Infrastructure Complaint",
      myTitle: "My Submissions",
      category: "Category",
      compTitle: "Complaint Title",
      compDesc: "Detailed Description",
      location: "Location / Address",
      priority: "Priority Level",
      photo: "Attach Photo of Damage / Problem",
      submitting: "Submitting...",
      successMsg: "Complaint submitted successfully!",
      noComplaints: "You have not submitted any complaints yet.",
      categoryLabel: "Category Filter",
      statusLabel: "Status Filter",
      officerNote: "Officer Note",
      rating: "Rate Resolution",
      officerTitle: "Infrastructure Complaints Management",
      stats: "Complaint Statistics",
      total: "Total",
      submitted: "Submitted",
      inProgress: "In Progress",
      resolved: "Resolved",
      rejected: "Rejected",
      complaintList: "Complaints List",
      updateModalTitle: "Update Complaint Status",
      assignee: "Assigned Officer/Department",
      note: "Officer Action Note"
    },
    election: {
      title: "Elections & Polling Portal",
      announcements: "Election Announcements",
      myReg: "My Voter Registration",
      checkReg: "Check Eligibility",
      noAnnouncements: "No active election announcements.",
      statusText: "Voter Registration Status",
      notRegistered: "You are not registered in the voter registry.",
      registered: "✓ Registered",
      division: "Polling Division",
      district: "Polling District",
      sheetNo: "Voter List Sheet No.",
      pollingStation: "Polling Station",
      serialNo: "Voter Serial Number",
      officerTitle: "Elections Management Portal",
      overview: "Overview",
      totalVoters: "Total Registered Voters",
      divisions: "Total Polling Divisions",
      activeElections: "Active Elections",
      announcementList: "Announcements List",
      postAnnouncement: "Post Announcement",
      electionDate: "Election Date",
      voterRegistry: "Voter Registry Database",
      addVoter: "Register New Voter",
      nic: "NIC Number",
      fullName: "Full Name",
      householdNo: "Household Number",
      registeredVoters: "Registered Voters",
      noVoters: "No registered voters found matching criteria."
    }
  },
  si: {
    nav: {
      noticeboard: "නිවේදන පුවරුව",
      appointments: "පත්වීම්",
      profile: "පැතිකඩ",
      certificates: "සහතික පත්‍ර",
      welfareApply: "සහනාධාර අයදුම්පත්",
      disaster: "🌊 ආපදා සේවා",
      complaints: "🏗️ යටිතල පහසුකම්",
      election: "🗳️ මැතිවරණ",
      gnDashboard: "ග්‍රාම නිලධාරී පුවරුව",
      welfareManage: "සහනාධාර කළමනාකරණය",
      systemSettings: "පද්ධති සැකසුම්",
      disasterManage: "ආපදා කළමනාකරණය",
      infraManage: "යටිතල පහසුකම් පාලනය",
      electionManage: "මැතිවරණ පාලනය",
      logout: "නික්ම යන්න",
      login: "ඇතුල් වන්න",
      register: "ලියාපදිංචි වන්න"
    },
    common: {
      loading: "පූරණය වෙමින්...",
      error: "දෝෂයකි",
      success: "සාර්ථකයි",
      submit: "යොමු කරන්න",
      cancel: "අවලංගු කරන්න",
      save: "සුරකින්න",
      delete: "මකා දමන්න",
      edit: "සංස්කරණය",
      update: "යාවත්කාලීන කරන්න",
      status: "තත්ත්වය",
      action: "ක්‍රියාව",
      pending: "බලාපොරොත්තු වන",
      approved: "අනුමතයි",
      rejected: "ප්‍රතික්ෂේපිත",
      active: "ක්‍රියාකාරී",
      suspended: "අත්හිටුවන ලද",
      resolved: "විසඳන ලද"
    },
    disaster: {
      title: "ආපදා සහ හදිසි තත්ත්ව ද්වාරය",
      sos: "SOS",
      sendSos: "හදිසි SOS පණිවිඩයක් යවන්න",
      alerts: "හදිසි ආපදා ඇඟවීම්",
      shelters: "ආරක්ෂිත නවාතැන්",
      mySos: "මගේ SOS ඉතිහාසය",
      contacts: "හදිසි ඇමතුම්",
      noAlerts: "මෙම අවස්ථාවේ සක්‍රීය හදිසි ඇඟවීම් කිසිවක් නොමැත.",
      noShelters: "ලියාපදිංචි ආරක්ෂිත නවාතැන් කිසිවක් නැත.",
      noSos: "ඔබ කිසිදු SOS ඉල්ලීමක් යොමු කර නොමැත.",
      sosFormTitle: "හදිසි SOS ඉල්ලුම්පත",
      sosFormHelp: "ඔබට අවශ්‍ය සහය කුමක්ද?",
      sosFormLoc: "වත්මන් ස්ථානය / ලිපිනය",
      sosFormDesc: "අතිරේක තොරතුරු (තුවාල ලැබූවන්, අවදානම් ආදී)",
      sosFormPersons: "බලපෑමට ලක්වූ පුද්ගලයන් ගණන",
      submitting: "යොමු වෙමින්...",
      sosSubmitted: "SOS ඉල්ලීම සාර්ථකව යොමු කරන ලදී! බලධාරීන් දැනුවත් කර ඇත.",
      capacity: "ධාරිතාව",
      facilities: "පහසුකම්",
      callNow: "දැන් අමතන්න",
      officerTitle: "ආපදා කළමනාකරණ නිලධාරී පිටුව",
      overview: "දළ විශ්ලේෂණය",
      totalAlerts: "මුළු ඇඟවීම් ගණන",
      activeAlerts: "සක්‍රීය ඇඟවීම්",
      totalSos: "මුළු SOS ඉල්ලීම්",
      pendingSos: "විසඳීමට ඇති SOS",
      postAlert: "නව ඇඟවීමක් පළ කරන්න",
      editAlert: "ඇඟවීම් සංස්කරණය",
      alertTitle: "ඇඟවීමේ මාතෘකාව",
      severity: "බරපතලකම",
      affectedArea: "බලපෑමට ලක්වූ ප්‍රදේශය",
      instructions: "උපදෙස්",
      low: "අඩු",
      medium: "මධ්‍යම",
      high: "වැඩි",
      critical: "අතිශය බරපතල",
      sosRequests: "SOS ඉල්ලීම් ලැයිස්තුව",
      markProgress: "ක්‍රියාත්මක වෙමින් පවතී",
      resolve: "විසඳන ලදී",
      addNote: "විසඳුම් සටහන ඇතුළත් කරන්න"
    },
    infra: {
      title: "යටිතල පහසුකම් ගැටළු ද්වාරය",
      submitTitle: "ගැටළුවක් යොමු කරන්න",
      myTitle: "මගේ පැමිණිලි",
      category: "ප්‍රවර්ගය",
      compTitle: "පැමිණිලි මාතෘකාව",
      compDesc: "විස්තරාත්මක විස්තරය",
      location: "ස්ථානය / ලිපිනය",
      priority: "ප්‍රමුඛතාව",
      photo: "හානියේ / ගැටළුවේ ඡායාරූපය ඇතුළත් කරන්න",
      submitting: "යොමු වෙමින්...",
      successMsg: "යටිතල පහසුකම් පැමිණිල්ල සාර්ථකව ඇතුළත් කරන ලදී!",
      noComplaints: "ඔබ තවමත් කිසිදු පැමිණිල්ලක් ඉදිරිපත් කර නොමැත.",
      categoryLabel: "ප්‍රවර්ගය අනුව පෙරන්න",
      statusLabel: "තත්ත්වය අනුව පෙරන්න",
      officerNote: "නිලධාරී සටහන",
      rating: "විසඳුම තක්සේරු කරන්න",
      officerTitle: "යටිතල පහසුකම් පැමිණිලි කළමනාකරණය",
      stats: "පැමිණිලි සංඛ්‍යාලේඛන",
      total: "එකතුව",
      submitted: "ඉදිරිපත් කළ",
      inProgress: "ක්‍රියාත්මක වෙමින් පවතින",
      resolved: "විසඳන ලද",
      rejected: "ප්‍රතික්ෂේපිත",
      complaintList: "පැමිණිලි ලැයිස්තුව",
      updateModalTitle: "පැමිණිලි තත්ත්වය යාවත්කාලීන කරන්න",
      assignee: "පැවරූ නිලධාරියා / අංශය",
      note: "ක්‍රියාමාර්ග සටහන"
    },
    election: {
      title: "මැතිවරණ සහ ඡන්ද ද්වාරය",
      announcements: "මැතිවරණ නිවේදන",
      myReg: "මගේ ඡන්ද ලියාපදිංචිය",
      checkReg: "සුදුසුකම් පරීක්ෂා කරන්න",
      noAnnouncements: "ක්‍රියාකාරී මැතිවරණ නිවේදන කිසිවක් නැත.",
      statusText: "ඡන්දදායක ලියාපදිංචි තත්ත්වය",
      notRegistered: "ඔබ ඡන්දහිමි නාමලේඛනයේ ලියාපදිංචි වී නොමැත.",
      registered: "✓ ලියාපදිංචි වී ඇත",
      division: "ඡන්ද කොට්ඨාශය",
      district: "ඡන්ද දිස්ත්‍රික්කය",
      sheetNo: "නෛතික පත්‍ර අංකය",
      pollingStation: "ඡන්ද මධ්‍යස්ථානය",
      serialNo: "ඡන්දදායක අනුක්‍රමික අංකය",
      officerTitle: "මැතිවරණ කළමනාකරණ ද්වාරය",
      overview: "දළ විශ්ලේෂණය",
      totalVoters: "ලියාපදිංචි මුළු ඡන්දදායකයින්",
      divisions: "මුළු ඡන්ද කොට්ඨාශ",
      activeElections: "ක්‍රියාකාරී මැතිවරණ",
      announcementList: "නිවේදන ලැයිස්තුව",
      postAnnouncement: "නිවේදනයක් පළ කරන්න",
      electionDate: "මැතිවරණ දිනය",
      voterRegistry: "ඡන්දහිමි නාමලේඛන දත්ත ගබඩාව",
      addVoter: "නව ඡන්දදායකයෙකු ලියාපදිංචි කරන්න",
      nic: "NIC අංකය",
      fullName: "සම්පූර්ණ නම",
      householdNo: "නිවාස අංකය",
      registeredVoters: "ලියාපදිංචි ඡන්දහිමියන්",
      noVoters: "සෙවුම් නිර්ණායකවලට අදාළ ඡන්දදායකයින් කිසිවෙකු හමු නොවීය."
    }
  },
  ta: {
    nav: {
      noticeboard: "அறிவிப்பு பலகை",
      appointments: "சந்திப்புகள்",
      profile: "சுயவிவரம்",
      certificates: "சான்றிதழ்கள்",
      welfareApply: "நலன்புரி விண்ணப்பம்",
      disaster: "🌊 பேரிடர்",
      complaints: "🏗️ புகார்கள்",
      election: "🗳️ தேர்தல்",
      gnDashboard: "அதிகாரி டாஷ்போர்டு",
      welfareManage: "நலன்புரி மேலாண்மை",
      systemSettings: "அமைப்பு அமைப்புகள்",
      disasterManage: "பேரிடர்",
      infraManage: "கட்டமைப்பு",
      electionManage: "தேர்தல்",
      logout: "வெளியேறு",
      login: "உள்நுழைக",
      register: "பதிவு செய்க"
    },
    common: {
      loading: "ஏற்றப்படுகிறது...",
      error: "பிழை",
      success: "வெற்றி",
      submit: "சமர்ப்பி",
      cancel: "ரத்து செய்",
      save: "சேமி",
      delete: "நீக்கு",
      edit: "தொகு",
      update: "புதுப்பி",
      status: "நிலை",
      action: "நடவடிக்கை",
      pending: "நிலுவையில் உள்ளது",
      approved: "அங்கீகரிக்கப்பட்டது",
      rejected: "நிராகரிக்கப்பட்டது",
      active: "செயலில் உள்ளது",
      suspended: "நிறுத்தி வைக்கப்பட்டுள்ளது",
      resolved: "தீர்வு காணப்பட்டது"
    },
    disaster: {
      title: "பேரிடர் மற்றும் அவசர சேவை மையம்",
      sos: "SOS",
      sendSos: "அவசர SOS அனுப்பவும்",
      alerts: "பேரிடர் எச்சரிக்கைகள்",
      shelters: "பாதுகாப்பான முகாம்கள்",
      mySos: "எனது SOS வரலாறு",
      contacts: "அவசர தொடர்புகள்",
      noAlerts: "செயலில் உள்ள பேரிடர் எச்சரிக்கைகள் எதுவுமில்லை.",
      noShelters: "பதிவு செய்யப்பட்ட முகாம்கள் எதுவுமில்லை.",
      noSos: "நீங்கள் எந்த SOS கோரிக்கையையும் சமர்ப்பிக்கவில்லை.",
      sosFormTitle: "அவசர SOS கோரிக்கை",
      sosFormHelp: "உங்களுக்கு என்ன உதவி தேவை?",
      sosFormLoc: "தற்போதைய இடம் / முகவரி",
      sosFormDesc: "கூடுதல் விபரங்கள் (காயங்கள், ஆபத்துகள்)",
      sosFormPersons: "பாதிக்கப்பட்ட நபர்களின் எண்ணிக்கை",
      submitting: "சமர்ப்பிக்கப்படுகிறது...",
      sosSubmitted: "SOS கோரிக்கை சமர்ப்பிக்கப்பட்டது! அதிகாரிகள் விரைந்து நடவடிக்கை எடுப்பர்.",
      capacity: "கொள்ளளவு",
      facilities: "வசதிகள்",
      callNow: "இப்போது அழைக்கவும்",
      officerTitle: "பேரிடர் மேலாண்மை அதிகாரி போர்டல்",
      overview: "கண்ணோட்டம்",
      totalAlerts: "மொத்த எச்சரிக்கைகள்",
      activeAlerts: "செயலில் உள்ள எச்சரிக்கைகள்",
      totalSos: "மொத்த SOS கோரிக்கைகள்",
      pendingSos: "தீர்க்கப்படாத SOS கோரிக்கைகள்",
      postAlert: "புதிய எச்சரிக்கை போஸ்ட் செய்",
      editAlert: "எச்சரிக்கையைத் திருத்து",
      alertTitle: "எச்சரிக்கை தலைப்பு",
      severity: "தீவிரம்",
      affectedArea: "பாதிக்கப்பட்ட பகுதி",
      instructions: "அறிவுறுத்தல்கள்",
      low: "குறைந்த",
      medium: "நடுத்தர",
      high: "அதிக",
      critical: "மிகவும் தீவிரமானது",
      sosRequests: "SOS கோரிக்கைகள் பட்டியல்",
      markProgress: "செயலாக்கத்தில் உள்ளது",
      resolve: "தீர்க்கப்பட்டது",
      addNote: "தீர்வு குறிப்பைச் சேர்க்கவும்"
    },
    infra: {
      title: "உள்கட்டமைப்பு சிக்கல் மையம்",
      submitTitle: "சிக்கலைச் சமர்ப்பிக்கவும்",
      myTitle: "எனது புகார்கள்",
      category: "வகை",
      compTitle: "புகார் தலைப்பு",
      compDesc: "விரிவான விளக்கம்",
      location: "இடம் / முகவரி",
      priority: "முன்னுரிமை நிலை",
      photo: "சேதத்தின் புகைப்படத்தை இணைக்கவும்",
      submitting: "சமர்ப்பிக்கப்படுகிறது...",
      successMsg: "உள்கட்டமைப்பு புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
      noComplaints: "நீங்கள் இன்னும் எந்த புகாரையும் சமர்ப்பிக்கவில்லை.",
      categoryLabel: "வகை மூலம் வடிகட்டு",
      statusLabel: "நிலை மூலம் வடிகட்டு",
      officerNote: "அதிகாரியின் குறிப்பு",
      rating: "தீர்வை மதிப்பிடுங்கள்",
      officerTitle: "உள்கட்டமைப்பு புகார்கள் மேலாண்மை",
      stats: "புகார் புள்ளிவிவரங்கள்",
      total: "மொத்தம்",
      submitted: "சமர்ப்பிக்கப்பட்டது",
      inProgress: "செயலாக்கத்தில் உள்ளது",
      resolved: "தீர்க்கப்பட்டது",
      rejected: "நிராகரிக்கப்பட்டது",
      complaintList: "புகார்கள் பட்டியல்",
      updateModalTitle: "புகார் நிலையைப் புதுப்பி",
      assignee: "ஒதுக்கப்பட்ட அதிகாரி / துறை",
      note: "அதிகாரியின் குறிப்பு"
    },
    election: {
      title: "தேர்தல்கள் மற்றும் வாக்களிப்பு மையம்",
      announcements: "தேர்தல் அறிவிப்புகள்",
      myReg: "எனது வாக்காளர் பதிவு",
      checkReg: "தகுதியைச் சரிபார்",
      noAnnouncements: "செயலில் உள்ள தேர்தல் அறிவிப்புகள் எதுவுமில்லை.",
      statusText: "வாக்காளர் பதிவு நிலை",
      notRegistered: "நீங்கள் வாக்காளர் பதிவேட்டில் பதிவு செய்யப்படவில்லை.",
      registered: "✓ பதிவு செய்யப்பட்டுள்ளது",
      division: "வாக்குப்பதிவு பிரிவு",
      district: "வாக்குப்பதிவு மாவட்டம்",
      sheetNo: "வாக்காளர் பட்டியல் தாள் எண்",
      pollingStation: "வாக்குச்சாவடி",
      serialNo: "வாக்காளர் வரிசை எண்",
      officerTitle: "தேர்தல் மேலாண்மை போர்டல்",
      overview: "கண்ணோட்டம்",
      totalVoters: "பதிவு செய்யப்பட்ட மொத்த வாக்காளர்கள்",
      divisions: "மொத்த வாக்குப்பதிவு பிரிவுகள்",
      activeElections: "செயலில் உள்ள தேர்தல்கள்",
      announcementList: "அறிவிப்புகள் பட்டியல்",
      postAnnouncement: "அறிவிப்பை போஸ்ட் செய்",
      electionDate: "தேர்தல் தேதி",
      voterRegistry: "வாக்காளர் பதிவேடு தரவுத்தளம்",
      addVoter: "புதிய வாக்காளரை பதிவு செய்",
      nic: "NIC எண்",
      fullName: "முழு பெயர்",
      householdNo: "வீட்டு எண்",
      registeredVoters: "பதிவு செய்யப்பட்ட வாக்காளர்கள்",
      noVoters: "தேடல் அளவுகோல்களுடன் பொருந்தும் வாக்காளர்கள் யாரும் இல்லை."
    }
  }
};
